[project]
authors = ["Chao-Chung Kuo <jovesus@gmail.com>"]
channels = ["conda-forge"]
name = "classifyanything"
platforms = ["osx-arm64"]
version = "0.1.0"

[tasks]

[dependencies]
pandas = ">=2.3.0,<3"
numpy = ">=2.3.1,<3"
matplotlib = ">=3.10.3,<4"
seaborn = ">=0.13.2,<0.14"
ipykernel = ">=6.29.5,<7"
toml = ">=0.10.2,<0.11"
scikit-learn = ">=1.7.0,<2"
nbconvert = ">=7.16.6,<8"
quarto = ">=1.7.32,<2"
pyyaml = ">=6.0.2,<7"
plotly = ">=6.2.0,<7"
xgboost = ">=3.0.2,<4"
lightgbm = ">=4.6.0,<5"
imbalanced-learn = ">=0.12.4,<0.13"
scipy = ">=1.15.2,<2"
